-- Run after creating test users in Supabase Auth.
-- Replace the UUIDs below with the corresponding auth.users ids.
--
-- insert into public.profiles (id, role, full_name) values
--   ('ADMIN_AUTH_UUID', 'admin', 'Ana Ferreira'),
--   ('TRAINER_AUTH_UUID', 'trainer', 'Rafael Mendes'),
--   ('STUDENT_AUTH_UUID', 'student', 'Marina Silva');
--
-- insert into public.professionals (profile_id, specialty)
-- values ('TRAINER_AUTH_UUID', 'Treinamento personalizado');
--
-- insert into public.students (profile_id, goal)
-- values ('STUDENT_AUTH_UUID', 'Força e composição corporal');
