import type {
  Announcement,
  Appointment,
  Credit,
  Exercise,
  ExtraClass,
  Invoice,
  LeagueAchievement,
  LeagueMember,
  PublicProfessional,
} from "@/lib/types";

export const student = {
  name: "Marina Silva",
  firstName: "Marina",
  goal: "Força e composição corporal",
  trainer: "Rafael Mendes",
  memberSince: "Novembro de 2025",
  streak: 8,
  attendance: 92,
  sessionsThisMonth: 11,
  plan: "Shift Performance",
  planStatus: "Ativo",
  accessSuspended: false,
  nextDueDate: "15 Jun 2026",
};

export const appointments: Appointment[] = [
  {
    id: "apt-1",
    service: "Treino",
    professional: "Rafael Mendes",
    date: "10 Jun",
    time: "07:00",
    duration: 60,
    status: "confirmed",
    location: "Sala Performance",
  },
  {
    id: "apt-2",
    service: "Recovery",
    professional: "Camila Nunes",
    date: "13 Jun",
    time: "18:30",
    duration: 40,
    status: "confirmed",
    location: "Espaço Recovery",
  },
  {
    id: "apt-3",
    service: "Treino",
    professional: "Rafael Mendes",
    date: "14 Jun",
    time: "09:00",
    duration: 60,
    status: "confirmed",
    location: "Sala Performance",
  },
];

export const credits: Credit[] = [
  {
    service: "Recovery",
    available: 1,
    nextRenewal: "01 Jul",
    detail: "Crédito mensal disponível",
  },
  {
    service: "Fisioterapia",
    available: 1,
    detail: "Disponível para agendamento",
  },
  {
    service: "Nutrição",
    available: 0,
    nextRenewal: "28 Jun",
    detail: "Próxima liberação configurada",
  },
];

export const todayWorkout: Exercise[] = [
  {
    name: "Agachamento no hack",
    sets: 4,
    reps: "8-10",
    load: "70 kg",
    rest: "90s",
    completed: true,
  },
  {
    name: "Leg press unilateral",
    sets: 3,
    reps: "10 cada",
    load: "40 kg",
    rest: "60s",
  },
  {
    name: "Remada articulada",
    sets: 4,
    reps: "10-12",
    load: "32 kg",
    rest: "75s",
  },
  {
    name: "Desenvolvimento",
    sets: 3,
    reps: "10",
    load: "12 kg",
    rest: "60s",
  },
];

export const progress = [
  { month: "Jan", strength: 64, frequency: 76 },
  { month: "Fev", strength: 68, frequency: 82 },
  { month: "Mar", strength: 73, frequency: 78 },
  { month: "Abr", strength: 78, frequency: 88 },
  { month: "Mai", strength: 84, frequency: 92 },
  { month: "Jun", strength: 89, frequency: 92 },
];

export const trainerSchedule = [
  { time: "06:00", students: ["Paulo N."], capacity: 2, status: "done" },
  {
    time: "07:00",
    students: ["Marina S.", "Bruno A."],
    capacity: 2,
    status: "next",
  },
  { time: "08:00", students: ["Cláudia R."], capacity: 2, status: "open" },
  { time: "09:00", students: [], capacity: 2, status: "open" },
  { time: "10:00", students: ["Gustavo M."], capacity: 2, status: "open" },
];

export const adminStats = [
  { label: "Alunos ativos", value: "148", change: "+8 este mês" },
  { label: "Ocupação semanal", value: "87%", change: "+4,2%" },
  { label: "Treinos hoje", value: "46", change: "8 profissionais" },
  { label: "Recovery", value: "12", change: "3 vagas livres" },
];

export const extraClasses: ExtraClass[] = [
  {
    id: "flow-sat-0800",
    kind: "Shift Flow",
    subtitle: "Bike · Ritmo & resistência",
    date: "13 Jun",
    dayLabel: "Sábado",
    time: "08:00",
    professional: "Paula Torres",
    location: "Studio Flow",
    capacity: 14,
    booked: 11,
    duration: 45,
    bookingState: "open",
    attendance: "booked",
  },
  {
    id: "move-sat-1000",
    kind: "Shift Move",
    subtitle: "Funcional · Mobilidade & potência",
    date: "13 Jun",
    dayLabel: "Sábado",
    time: "10:00",
    professional: "Rafael Mendes",
    location: "Área Funcional",
    capacity: 12,
    booked: 8,
    duration: 50,
    bookingState: "open",
    attendance: "booked",
  },
  {
    id: "flow-sun-0900",
    kind: "Shift Flow",
    subtitle: "Bike · Endurance session",
    date: "14 Jun",
    dayLabel: "Domingo",
    time: "09:00",
    professional: "Paula Torres",
    location: "Studio Flow",
    capacity: 14,
    booked: 14,
    duration: 45,
    bookingState: "full",
    attendance: "booked",
  },
  {
    id: "move-sun-1030",
    kind: "Shift Move",
    subtitle: "Funcional · Corpo inteiro",
    date: "14 Jun",
    dayLabel: "Domingo",
    time: "10:30",
    professional: "Rafael Mendes",
    location: "Área Funcional",
    capacity: 12,
    booked: 5,
    duration: 50,
    bookingState: "soon",
    attendance: "booked",
  },
];

export const announcements: Announcement[] = [
  {
    id: "notice-1",
    title: "Shift Flow neste sábado",
    body: "A agenda abre na quarta-feira às 08:00. São 14 bikes disponíveis para uma aula especial de endurance.",
    publishedAt: "Hoje, 08:15",
    expiresAt: "13 Jun",
    priority: "important",
    pinned: true,
    read: false,
  },
  {
    id: "notice-2",
    title: "Avaliações físicas de junho",
    body: "Converse com seu professor para conferir a melhor janela para atualizar medidas, fotos e objetivos do próximo ciclo.",
    publishedAt: "8 Jun, 17:40",
    priority: "normal",
    pinned: false,
    read: false,
  },
  {
    id: "notice-3",
    title: "Horário especial no feriado",
    body: "Na próxima quinta-feira, a unidade funcionará das 08:00 às 14:00. Os horários já estão disponíveis no portal.",
    publishedAt: "6 Jun, 12:10",
    expiresAt: "18 Jun",
    priority: "urgent",
    pinned: false,
    read: true,
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv-jun",
    reference: "Junho de 2026",
    dueDate: "15 Jun 2026",
    amount: 1400,
    status: "pending",
  },
  {
    id: "inv-may",
    reference: "Maio de 2026",
    dueDate: "15 Mai 2026",
    paidAt: "13 Mai 2026",
    amount: 1400,
    status: "paid",
  },
  {
    id: "inv-apr",
    reference: "Abril de 2026",
    dueDate: "15 Abr 2026",
    paidAt: "15 Abr 2026",
    amount: 1400,
    status: "paid",
  },
  {
    id: "inv-mar",
    reference: "Março de 2026",
    dueDate: "15 Mar 2026",
    paidAt: "14 Mar 2026",
    amount: 1400,
    discount: 100,
    status: "paid",
  },
];

export const publicProfessionals: PublicProfessional[] = [
  {
    id: "rafael",
    name: "Rafael Mendes",
    role: "Head Coach",
    specialties: ["Força", "Hipertrofia", "Performance"],
    modalities: ["Treino personalizado", "Shift Move"],
    bio: "Transforma avaliação e objetivo em um treino preciso, progressivo e sustentável. Lidera o método de força da Shift.",
    image: "/images/shift-coaching.jpeg",
    imagePosition: "center 30%",
    instagram: "@rafael.shift",
  },
  {
    id: "paula",
    name: "Paula Torres",
    role: "Coach",
    specialties: ["Bike", "Condicionamento", "Mobilidade"],
    modalities: ["Treino personalizado", "Shift Flow"],
    bio: "Combina energia e leitura técnica para criar sessões intensas, acolhedoras e ajustadas ao ritmo de cada aluno.",
    image: "/images/shift-performance.jpeg",
    imagePosition: "center 35%",
    instagram: "@paula.shift",
  },
  {
    id: "camila",
    name: "Camila Nunes",
    role: "Recovery Specialist",
    specialties: ["Recovery", "Mobilidade", "Regeneração"],
    modalities: ["Recovery"],
    bio: "Cuida da recuperação como parte do processo de performance, conectando mobilidade, descanso e prontidão para o próximo treino.",
    image: "/images/shift-detail.jpeg",
    imagePosition: "center",
  },
  {
    id: "lucas",
    name: "Lucas Prado",
    role: "Fisioterapeuta",
    specialties: ["Prevenção", "Reabilitação", "Movimento"],
    modalities: ["Fisioterapia"],
    bio: "Avalia padrões de movimento e conduz intervenções para que o aluno evolua com segurança e confiança.",
    image: "/images/shift-experience.jpeg",
    imagePosition: "center 30%",
  },
];

export const hourlyCheckins = [
  {
    time: "09:00",
    service: "Treino personalizado",
    professional: "Rafael Mendes",
    capacity: 2,
    students: [
      { name: "Marina Silva", state: "checked_in" },
      { name: "Bruno Alves", state: "booked" },
    ],
  },
  {
    time: "10:00",
    service: "Treino personalizado",
    professional: "Rafael Mendes",
    capacity: 2,
    students: [{ name: "Gustavo Melo", state: "booked" }],
  },
  {
    time: "11:00",
    service: "Treino personalizado",
    professional: "Paula Torres",
    capacity: 2,
    students: [
      { name: "Cláudia Reis", state: "absent" },
      { name: "Renata Lima", state: "cancelled" },
    ],
  },
  {
    time: "12:00",
    service: "Treino personalizado",
    professional: "Paula Torres",
    capacity: 2,
    students: [],
  },
] as const;

export const leagueRanking: LeagueMember[] = [
  {
    position: 1,
    name: "Gustavo M.",
    initials: "GM",
    checkins: 18,
    streak: 9,
    movement: "same",
  },
  {
    position: 2,
    name: "Paulo N.",
    initials: "PN",
    checkins: 16,
    streak: 7,
    movement: "up",
  },
  {
    position: 3,
    name: "Cláudia R.",
    initials: "CR",
    checkins: 14,
    streak: 6,
    movement: "down",
  },
  {
    position: 4,
    name: "Bruno A.",
    initials: "BA",
    checkins: 12,
    streak: 5,
    movement: "up",
  },
  {
    position: 5,
    name: "Marina S.",
    initials: "MS",
    checkins: 11,
    streak: 8,
    movement: "up",
    isCurrentStudent: true,
  },
  {
    position: 6,
    name: "Renata L.",
    initials: "RL",
    checkins: 10,
    streak: 4,
    movement: "down",
  },
  {
    position: 7,
    name: "Juliana S.",
    initials: "JS",
    checkins: 9,
    streak: 3,
    movement: "same",
  },
  {
    position: 8,
    name: "Felipe C.",
    initials: "FC",
    checkins: 8,
    streak: 4,
    movement: "up",
  },
];

export const leagueAchievements: LeagueAchievement[] = [
  {
    id: "first-five",
    title: "Ritmo encontrado",
    description: "Complete 5 check-ins no mês.",
    unlocked: true,
    progress: 5,
    target: 5,
  },
  {
    id: "ten-club",
    title: "Clube dos 10",
    description: "Complete 10 check-ins no mês.",
    unlocked: true,
    progress: 10,
    target: 10,
  },
  {
    id: "weekend",
    title: "Weekend Shift",
    description: "Participe de uma aula Flow ou Move.",
    unlocked: true,
    progress: 1,
    target: 1,
  },
  {
    id: "twenty",
    title: "20 em movimento",
    description: "Complete 20 check-ins no mês.",
    unlocked: false,
    progress: 11,
    target: 20,
  },
];
